### PR TITLE
Enable CXX11 if possible.

### PR DESCRIPTION
**Pull request by stephanmg**
Proposed change to detect C++11 compatible compiler and add CMake flags.

### CODE REVIEW

**Comment by sreiter** [comment]
Hey Stephan,
I think your current approach works for gcc and clang only (maybe some more). CMake offers a pretty clean way to enable different standards for individual targets:
```cmake
target_compile_features (someTarget PUBLIC cxx_std_11)
```
If you would enable this on ugcore, all targets which link against ugcore would autmoatically use c++11, too.

Maybe this is of interest: https://cmake.org/cmake/help/latest/manual/cmake-compile-features.7.html#id1

Regards,
Sebastian

**Comment by mlampe** [comment]
@stephanmg: There already is _ugcore/cmake/ug/cpp11.cmake_ with the same intent. Wants to be enabled with `-DCXX11=ON` though.

@sreiter: Seems that this requires a much more recent version of cmake. Currently, we claim to work with 2.6+.

What about defaulting to `CXX11=ON` as a temporary solution?

**Comment by stephanmg** [comment]
Thanks for your valuable comments. I'm closing this PR. (Invalid)

**Comment by LogashenkoDL** [comment]
But we need it under MSWin theoretically, too. Will it work with VS? Is the 
version 2.6 of cmake an essential requirement?

**Comment by mlampe** [comment]
> Will it work with VS?

AppVeyor says yes. That's because VS 2017 defaults to C++14.

**Pull request closed without merging**
